# Generated by Django 5.0.1 on 2024-12-25 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyects', '0002_remove_project_factured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='annotations',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='project',
            name='in_contrat',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='in_dev',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='in_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='in_quality',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('Terminado', 'Terminado'), ('Atrasado', 'Atrasado'), ('Detenido', 'Detenido'), ('Interrumpido', 'Interrumpido'), ('En proceso', 'En proceso')], default='Terminado', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='service_type',
            field=models.CharField(choices=[('Proyecto', 'Proyecto'), ('Proyecto Interno', 'Proyecto Interno'), ('Proyecto Asociado', 'Proyecto Asociado'), ('Servicio', 'Servicio')], max_length=20),
        ),
    ]
