# Generated by Django 5.0.1 on 2024-12-26 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyects', '0002_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='month',
            old_name='month',
            new_name='name',
        ),
    ]
