# Generated by Django 5.0.1 on 2024-12-25 21:14

import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyects', '0003_project_annotations_project_in_contrat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='id',
        ),
        migrations.AddField(
            model_name='project',
            name='number',
            field=models.SmallAutoField(default=1, primary_key=True, serialize=False, verbose_name='No.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='annotations',
            field=models.TextField(blank=True, max_length=250, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='project',
            name='factured_payment',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='CUP', max_digits=9, verbose_name='Facturado'),
        ),
        migrations.AlterField(
            model_name='project',
            name='in_contrat',
            field=models.BooleanField(default=False, verbose_name='Contratación'),
        ),
        migrations.AlterField(
            model_name='project',
            name='in_dev',
            field=models.BooleanField(default=False, verbose_name='En desarrollo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='in_plan',
            field=models.BooleanField(default=False, verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='project',
            name='in_quality',
            field=models.BooleanField(default=False, verbose_name='Calidad'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='Terminado'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Proyect/Servicio'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pending_payment',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0.0'), default_currency='CUP', max_digits=9, verbose_name='Pendiente'),
        ),
        migrations.AlterField(
            model_name='project',
            name='responsable',
            field=models.CharField(max_length=20, verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='project',
            name='service_type',
            field=models.CharField(choices=[('Proyecto', 'Proyecto'), ('Proyecto Interno', 'Proyecto Interno'), ('Proyecto Asociado', 'Proyecto Asociado'), ('Servicio', 'Servicio')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.CharField(choices=[('Terminado', 'Terminado'), ('Atrasado', 'Atrasado'), ('Detenido', 'Detenido'), ('Interrumpido', 'Interrumpido'), ('En proceso', 'En proceso')], max_length=20, verbose_name='Estado Proyecto'),
        ),
    ]
