# Generated by Django 5.0.1 on 2024-12-26 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyects', '0003_rename_month_month_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='month',
            old_name='name',
            new_name='month',
        ),
    ]
