# Generated by Django 5.0.1 on 2024-12-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyects', '0004_remove_project_id_project_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Proyecto/Servicio'),
        ),
    ]
