# Generated by Django 5.0.1 on 2024-12-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyects', '0004_rename_name_month_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='plan',
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=9, verbose_name='Plan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='month',
            name='real',
            field=models.DecimalField(decimal_places=2, default=1.1, max_digits=9, verbose_name='Real'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='month',
            name='month',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], verbose_name='Mes'),
        ),
    ]
