# Generated by Django 5.0.1 on 2024-12-25 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyects', '0007_project_factured_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='factured_payment',
        ),
        migrations.RemoveField(
            model_name='project',
            name='factured_payment_currency',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pending_payment',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pending_payment_currency',
        ),
    ]
