# Generated by Django 5.0.1 on 2024-12-26 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveSmallIntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], verbose_name='Mes')),
                ('plan', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Plan')),
                ('real', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Real')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('number', models.SmallAutoField(primary_key=True, serialize=False, verbose_name='No.')),
                ('name', models.CharField(max_length=20, verbose_name='Proyecto/Servicio')),
                ('code', models.CharField(blank=True, max_length=6, null=True, unique=True, verbose_name='Código')),
                ('service_type', models.CharField(choices=[('Proyecto', 'Proyecto'), ('Proyecto Interno', 'Proyecto Interno'), ('Proyecto Asociado', 'Proyecto Asociado'), ('Servicio', 'Servicio')], max_length=20, verbose_name='Tipo')),
                ('responsable', models.CharField(max_length=20, verbose_name='Responsable')),
                ('factured_payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Facturado')),
                ('pending_payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Pendiente')),
                ('in_plan', models.BooleanField(default=False, verbose_name='Plan')),
                ('in_contrat', models.BooleanField(default=False, verbose_name='Contratación')),
                ('in_dev', models.BooleanField(default=False, verbose_name='En desarrollo')),
                ('in_quality', models.BooleanField(default=False, verbose_name='Calidad')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Terminado')),
                ('state', models.CharField(choices=[('Terminado', 'Terminado'), ('Atrasado', 'Atrasado'), ('Detenido', 'Detenido'), ('Interrumpido', 'Interrumpido'), ('En proceso', 'En proceso')], max_length=20, verbose_name='Estado Proyecto')),
                ('annotations', models.TextField(blank=True, max_length=250, verbose_name='Observaciones')),
            ],
        ),
        migrations.CreateModel(
            name='Subproject',
            fields=[
                ('number', models.SmallAutoField(primary_key=True, serialize=False, verbose_name='No.')),
                ('service_type', models.CharField(choices=[('Proyecto', 'Proyecto'), ('Proyecto Interno', 'Proyecto Interno'), ('Proyecto Asociado', 'Proyecto Asociado'), ('Servicio', 'Servicio')], max_length=20, verbose_name='Tipo')),
                ('name', models.CharField(max_length=20, verbose_name='Proyecto/Servicio')),
                ('responsable', models.CharField(max_length=20, verbose_name='Responsable')),
                ('in_plan', models.BooleanField(default=False, verbose_name='Plan')),
                ('in_contrat', models.BooleanField(default=False, verbose_name='Contratación')),
                ('in_dev', models.BooleanField(default=False, verbose_name='En desarrollo')),
                ('in_quality', models.BooleanField(default=False, verbose_name='Calidad')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Terminado')),
                ('state', models.CharField(choices=[('Terminado', 'Terminado'), ('Atrasado', 'Atrasado'), ('Detenido', 'Detenido'), ('Interrumpido', 'Interrumpido'), ('En proceso', 'En proceso')], max_length=20, verbose_name='Estado Proyecto')),
                ('annotations', models.TextField(blank=True, max_length=250, verbose_name='Observaciones')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
    ]
