# Generated by Django 5.0.1 on 2025-01-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='plan',
            field=models.BigIntegerField(blank=True, default=1),
        ),
    ]
