# Generated by Django 5.0.1 on 2024-12-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_year_month_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='year',
            name='plan',
            field=models.PositiveBigIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='month',
            name='plan',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Plan'),
        ),
        migrations.AlterField(
            model_name='month',
            name='real',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Real'),
        ),
        migrations.AlterField(
            model_name='year',
            name='number',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='year',
            name='projects',
            field=models.ManyToManyField(blank=True, null=True, to='projects.project'),
        ),
    ]
