# Generated by Django 5.0.1 on 2024-12-28 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_year_plan_alter_month_plan_alter_month_real_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='year',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.ForeignKey(default=2024, on_delete=django.db.models.deletion.RESTRICT, to='projects.year'),
            preserve_default=False,
        ),
    ]
