# Generated by Django 5.0.1 on 2024-12-29 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_year_projects_project_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLink',
            fields=[
                ('link', models.URLField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('project_type', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Tipo de proyecto')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='projects.projecttype'),
        ),
    ]
