# Generated by Django 5.0.1 on 2024-12-29 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectlink_projecttype_alter_project_service_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectLink',
        ),
    ]
