# Generated by Django 5.0.1 on 2025-01-05 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_projectlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='projects.projecttype', verbose_name='Tipo de Proyecto'),
        ),
    ]
